// web/packages/ciafagent-ui-kit/src/ic-react/performance-tests/pages/IcFooter/index.tsx
/**
 * CIANCHOSAINT wholesale-copy of mi6/ic-ui-kit.
 *
 * Original: mi6/ic-ui-kit (https://github.com/mi6/ic-ui-kit, MIT + OGL-3.0).
 * Wholesale-copied into cianchosaint: 2026-08-26 per
 * openspec/changes/2026-08-26-cianchosaint-ic-ui-kit-integration-v1/
 * specs/cianchosaint-ic-ui-kit-integration/spec.md.
 *
 * Upstream licences (preserved):
 *   - MIT (https://github.com/mi6/ic-ui-kit/blob/main/LICENSE)
 *   - Open Government Licence v3.0 (https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/)
 *
 * Cianchosaint licence:
 *   - BUSL-1.1 v2 (CIANCHOSAINT edition, per LICENSE.md) — British-Isles-only.
 *   - This file is part of the ciafagent UI kit that wraps the IC Design System
 *     for British-Isles defence / policing / intelligence-oversight analysts.
 *
 * Namespace: cianchosaint (every reference is renamed from the upstream
 * `ukic` / `@ukic` package scope to the `cianchosaint` workspace scope
 * during build via the cianchosaint @ukic/* package aliases).
 */
// IcFooterPage displays a footer for the purpose of performance testing of the IcFooter component.
import React from "react";
import {
  IcFooter,
  IcFooterLink,
  IcClassificationBanner,
  IcTheme,
  IcTypography,
} from "../../../components";

type PageProps = {
  theme: "light" | "dark";
};

const IcFooterPage: React.FC<PageProps> = ({ theme }) => {
  return (
    <IcTheme id="theme-wrapper" theme={theme}>
      <IcTypography
        variant="subtitle-small"
        style={{ padding: "var(--ic-space-md)" }}
      >
        <h1>Footer Page</h1>
      </IcTypography>
      <>
        <IcClassificationBanner classification="official" />
        <IcFooter
          description="The ICDS is maintained by the Design Practice Team. If you've got a question or want to feedback, please get in touch."
          caption="All content is available under the Open Government Licence v3.0, except source code and code examples which are available under the MIT Licence."
          style={{ position: "fixed", bottom: "0", left: "0", right: "0" }}
        >
          <IcFooterLink slot="link" href="/">
            Get Started
          </IcFooterLink>
          <IcFooterLink slot="link" href="/">
            Accessibility
          </IcFooterLink>
          <IcFooterLink slot="link" href="/">
            Styles
          </IcFooterLink>
          <IcFooterLink slot="link" href="/">
            Components
          </IcFooterLink>
          <IcFooterLink slot="link" href="/">
            Patterns
          </IcFooterLink>
          <IcFooterLink slot="link" href="/">
            Design toolkit
          </IcFooterLink>
          <div
            slot="logo"
            role="list"
            style={{
              display: "flex",
              gap: "var(--ic-space-lg)",
            }}
          >
            <IcFooterLink href="/">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                height="48px"
                viewBox="0 0 24 24"
                width="48px"
                fill="#FFFFFF"
              >
                <title>Footer logo link 1</title>
                <path d="M0 0h24v24H0V0z" fill="none" />
                <path d="M19 5v14H5V5h14m0-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-4.86 8.86l-3 3.87L9 13.14 6 17h12l-3.86-5.14z" />
              </svg>
            </IcFooterLink>
            <IcFooterLink href="/">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                height="48px"
                viewBox="0 0 24 24"
                width="48px"
                fill="#FFFFFF"
              >
                <title>Footer logo link 2</title>
                <path d="M0 0h24v24H0V0z" fill="none" />
                <path d="M19 5v14H5V5h14m0-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-4.86 8.86l-3 3.87L9 13.14 6 17h12l-3.86-5.14z" />
              </svg>
            </IcFooterLink>
            <IcFooterLink href="/">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                height="48px"
                viewBox="0 0 24 24"
                width="48px"
                fill="#FFFFFF"
              >
                <title>Footer logo link 3</title>
                <path d="M0 0h24v24H0V0z" fill="none" />
                <path d="M19 5v14H5V5h14m0-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-4.86 8.86l-3 3.87L9 13.14 6 17h12l-3.86-5.14z" />
              </svg>
            </IcFooterLink>
          </div>
        </IcFooter>
      </>
    </IcTheme>
  );
};

export default IcFooterPage;

// web/packages/ciafagent-ui-kit/src/ic-web-components/ic-footer/ic-footer.tsx
/**
 * CIANCHOSAINT wholesale-copy of mi6/ic-ui-kit.
 *
 * Original: mi6/ic-ui-kit (https://github.com/mi6/ic-ui-kit, MIT + OGL-3.0).
 * Wholesale-copied into cianchosaint: 2026-08-26 per
 * openspec/changes/2026-08-26-cianchosaint-ic-ui-kit-integration-v1/
 * specs/cianchosaint-ic-ui-kit-integration/spec.md.
 *
 * Upstream licences (preserved):
 *   - MIT (https://github.com/mi6/ic-ui-kit/blob/main/LICENSE)
 *   - Open Government Licence v3.0 (https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/)
 *
 * Cianchosaint licence:
 *   - BUSL-1.1 v2 (CIANCHOSAINT edition, per LICENSE.md) — British-Isles-only.
 *   - This file is part of the ciafagent UI kit that wraps the IC Design System
 *     for British-Isles defence / policing / intelligence-oversight analysts.
 *
 * Namespace: cianchosaint (every reference is renamed from the upstream
 * `ukic` / `@ukic` package scope to the `cianchosaint` workspace scope
 * during build via the cianchosaint @ukic/* package aliases).
 */
import {
  Component,
  Element,
  Event,
  EventEmitter,
  h,
  Host,
  Listen,
  Prop,
  State,
} from "@stencil/core";
import { IC_DEVICE_SIZES } from "../../utils/constants";
import {
  getCurrentDeviceSize,
  getBrandForegroundAppearance,
  checkResizeObserver,
  hasClassificationBanner,
  isSlotUsed,
  renderDynamicChildSlots,
} from "../../utils/helpers";
import {
  IcAlignment,
  IcBrand,
  IcBrandForeground,
  IcBrandForegroundEnum,
} from "../../utils/types";
import { IcFooterBreakpoints } from "./ic-footer.types";

/**
 * @slot description - Content will be rendered at the top of the footer.
 * @slot link - Content will be rendered between description and logos.
 * @slot logo - Content will be rendered underneath footer links.
 * @slot caption - Content will be rendered above Crown Copyright.
 */

@Component({
  tag: "ic-footer",
  styleUrl: "ic-footer.css",
  shadow: true,
})
export class Footer {
  private footerEl?: HTMLElement;
  private resizeObserver: ResizeObserver | null = null;
  private hostMutationObserver: MutationObserver | null = null;

  @Element() el: HTMLIcFooterElement;

  @State() deviceSize: number = IC_DEVICE_SIZES.XL;
  @State() foregroundColor: IcBrandForeground = getBrandForegroundAppearance();

  /**
   * The alignment of the section containers used within the footer.
   */
  @Prop() aligned?: IcAlignment = "left";

  /**
   * The screen size breakpoint at which to switch to the small layout.
   */
  @Prop() breakpoint?: IcFooterBreakpoints = "medium";

  /**
   * The caption displayed at the bottom of the footer.
   */
  @Prop() caption?: string;

  /**
   * If `true`, the footer will display the crown copyright at the bottom.
   */
  @Prop() copyright?: boolean = true;

  /**
   * The text displayed for the copyright notice if `copyright` is `true`.
   */
  @Prop() copyrightText?: string = "© Crown Copyright";

  /**
   * The description displayed at the top of the footer.
   */
  @Prop() description?: string;

  /**
   * If `true`, the footer will be set up to handle link groups instead of standalone links.
   */
  @Prop() groupLinks?: boolean = false;

  /**
   *  @internal Triggers on page resize and triggers style changes in footer links and link groups
   */
  @Event() footerResized: EventEmitter<void>;

  disconnectedCallback(): void {
    if (this.resizeObserver !== null) {
      this.resizeObserver.disconnect();
    }

    this.hostMutationObserver?.disconnect();
  }

  componentWillLoad(): void {
    this.deviceSize = getCurrentDeviceSize();
  }

  componentDidLoad(): void {
    checkResizeObserver(this.runResizeObserver);

    this.hostMutationObserver = new MutationObserver((mutationList) => {
      return renderDynamicChildSlots(mutationList, "link", this);
    });

    this.hostMutationObserver.observe(this.el, {
      childList: true,
    });
  }

  @Listen("brandChange", { target: "document" })
  brandChangeHandler(ev: CustomEvent<IcBrand>): void {
    this.foregroundColor = ev.detail.mode;
  }

  private isSmall() {
    const bp = this.breakpoint;

    return bp === "extra small"
      ? this.deviceSize < IC_DEVICE_SIZES.XS
      : bp === "small"
      ? this.deviceSize < IC_DEVICE_SIZES.S
      : bp === "medium"
      ? this.deviceSize < IC_DEVICE_SIZES.M
      : bp === "large"
      ? this.deviceSize < IC_DEVICE_SIZES.L
      : bp === "extra large"
      ? this.deviceSize < IC_DEVICE_SIZES.XL
      : false;
  }

  private resizeObserverCallback = (currSize: number) => {
    if (currSize !== this.deviceSize) {
      this.deviceSize = currSize;
    }
    this.footerResized.emit();
  };

  private runResizeObserver = () => {
    if (this.footerEl) {
      this.resizeObserver = new ResizeObserver(() => {
        const currSize = getCurrentDeviceSize();
        this.resizeObserverCallback(currSize);
      });

      this.resizeObserver.observe(this.footerEl);
    }
  };

  render() {
    const {
      aligned,
      caption,
      copyright,
      copyrightText,
      description,
      deviceSize,
      el,
      foregroundColor,
      groupLinks,
    } = this;
    const small = this.isSmall();

    const showComplianceSection =
      isSlotUsed(el, "logo") ||
      isSlotUsed(el, "caption") ||
      caption ||
      copyright;

    return (
      <Host
        class={{
          ["ic-footer"]: true,
          [`ic-footer-${small ? "small" : "sparse"}`]: true,
          [`ic-footer-${groupLinks ? "grouped" : "ungrouped"}`]: true,
          [`ic-footer-foreground-${foregroundColor}`]: true,
          // Slots will be able to infer their own color
          [`ic-footer-${IcBrandForegroundEnum.Dark}`]:
            foregroundColor === IcBrandForegroundEnum.Dark,
          [`ic-footer-${IcBrandForegroundEnum.Light}`]:
            foregroundColor === IcBrandForegroundEnum.Light,
        }}
      >
        <footer ref={(el) => (this.footerEl = el)}>
          {/* Description */}
          {(isSlotUsed(el, "description") || description) && (
            <div class="footer-description">
              <ic-section-container aligned={aligned} fullHeight={true}>
                <div class="footer-description-inner">
                  <ic-typography variant="body">
                    <slot name="description">{description}</slot>
                  </ic-typography>
                </div>
              </ic-section-container>
            </div>
          )}

          {/* Links */}
          {isSlotUsed(el, "link") && (
            <div class="footer-links">
              {groupLinks && small ? (
                <div class="footer-links-inner" role="list">
                  <slot name="link" />
                </div>
              ) : (
                <ic-section-container fullHeight aligned={aligned}>
                  <div class="footer-links-inner" role="list">
                    <slot name="link" />
                  </div>
                </ic-section-container>
              )}
            </div>
          )}

          {/* Compliance (logo, caption, copyright) */}
          {showComplianceSection && (
            <div class="footer-compliance">
              <ic-section-container aligned={aligned} fullHeight={true}>
                <div class="footer-compliance-inner">
                  {isSlotUsed(el, "logo") && (
                    <div class="footer-logo">
                      <slot name="logo" />
                    </div>
                  )}
                  {(isSlotUsed(el, "caption") || caption) && (
                    <div class="footer-caption">
                      <ic-typography
                        variant={
                          deviceSize <= IC_DEVICE_SIZES.M ? "caption" : "body"
                        }
                      >
                        <slot name="caption">{caption}</slot>
                      </ic-typography>
                    </div>
                  )}
                  {copyright && (
                    <div
                      class={{
                        ["footer-copyright"]: true,
                        ["classification-spacing"]: hasClassificationBanner(),
                      }}
                    >
                      <ic-typography
                        variant={
                          deviceSize <= IC_DEVICE_SIZES.M
                            ? "caption-uppercase"
                            : "label-uppercase"
                        }
                      >
                        {copyrightText}
                      </ic-typography>
                    </div>
                  )}
                </div>
              </ic-section-container>
            </div>
          )}
        </footer>
      </Host>
    );
  }
}
